# .github/workflows/test_Using_built-in_Postgres_service_in_Actions.yml
name: Test_Using_built-in_Postgres_service_in_Actions

on:
  push:
    branches:
      - main
      - 'PA-*'
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: parking_test
        # wait until Postgres is ready
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest psycopg2-binary

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run tests
        env:
          TESTING: "True"
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: parking_test
          DB_USER: postgres
          DB_PASSWORD: root
          JWT_SECRET_KEY: your-secret-key-here
        run: |
          pytest --verbose
